# @package _global_
benchmark:
  name: oie
  raw_path: modules/model/evaluation/oie-benchmark-stanovsky/oie_corpus/all.oie
  processed_path: modules/model/evaluation/oie-benchmark-stanovsky/oie_corpus/ours.oie
